### ISSUE TITLE
Not an editor command: CodeExplain

### ISSUE THREAD

**Issue by itz-Jana** [mthbernardes/codeexplain.nvim#1]
Hi,
I've installed CodeExplain using vim-plug, run :PlugInstall successfully and downloaded the model to the .codeexplain folder.
Sadly NVIM doesn't seem to recognise the Plugin and doesn't find the Command, it's also not listed in :command.

Are there any additional steps I need to take to make this plugin work?

**Comment by Bacbia3696** [comment]
I am on M1 with nvim 0.10, and I have the same issue as you.

**Comment by mthbernardes** [comment]
I've tested it on `packer` and no additional step was necessary. Did you install all python dependencies?
`pip install pynvim langchain pygments`

**Comment by mthbernardes** [comment]
I was reading the readme and I saw that it's missing a step. After all inside nvim you need to call the command `:UpdateRemotePlugins`
