### ISSUE TITLE
InMemoryCache is not defind

### ISSUE THREAD

**Issue by iamDrakkir** [mthbernardes/codeexplain.nvim#2]
I have installed the package and the python dependencies. 

but when i run :CodeExplain

I get errors 
![Screenshot from 2023-05-26 14-56-58](https://github.com/mthbernardes/codeexplain.nvim/assets/38097580/b98aa304-2ce8-4dfd-aa8f-f0894e7f95bf)

I can fix it by adding `from langchain.cache import InMemoryCache` to codeExplain.py 

But then i get this error instead: 
![image](https://github.com/mthbernardes/codeexplain.nvim/assets/38097580/1695e365-1691-447f-9e92-f48c692f95d8)

but then i am lost and don't know how to fix it :P

**Comment by mthbernardes** [comment]
Could you try to change the model and use this one.
https://gpt4all.io/models/ggml-vicuna-7b-1.1-q4_2.bin
It seems to be working.

**Comment by iamDrakkir** [comment]
get error that it could not load Llama model for that one.
![image](https://github.com/mthbernardes/codeexplain.nvim/assets/38097580/03d52dd9-8204-4a97-895e-d6792c4d190c)

the path seems to be correct and the file is there :disappointed: 

Also updated to the latest version so the InMemoryCache is removed :+1:

**Comment by mthbernardes** [comment]
Can you confirm that the md5 of the model is this one `29119f8fa11712704c6b22ac5ab792ea`

**Comment by iamDrakkir** [comment]
yep 
![image](https://github.com/mthbernardes/codeexplain.nvim/assets/38097580/33c4530f-426f-4d5d-9160-32fc077e5f0d)

and the same model woks with gpt4all
![image](https://github.com/mthbernardes/codeexplain.nvim/assets/38097580/def2ed9f-113e-4f8d-920a-f4605ec9226a)

**Comment by mthbernardes** [comment]
I figure it out here, it's necessary to install this exact versions of the dependencies.
```
langchain==0.0.177
llama-cpp-python==0.1.48
Pygments==2.15.1
pynvim==0.4.3
```

**Comment by iamDrakkir** [comment]
Indeed that worked!
Good job finding the issue :+1:
